### ISSUE TITLE
Newman --reporter-cli-no-assertions option prevents cli output

### ISSUE THREAD

**Issue by htmtester** [postmanlabs/newman#1367]
Version and environment information:
 1. Newman Version = 3.9.1
 2. OS details = Win7, 64 bits
 3. Using via CLI
Node version = 8.9.4

I am trying to run my collections and to avoid the passed assertions output I used the parameter --reporter-cli-no-assertions and it worked perfectly once. Problem is now that whenever I use this option there is not any output in command line, execution completes but there are no more details like before. Only the summary appears.

**Comment by kunagpal** [comment]
@htmtester Apologies for the delay, and thanks for reporting this. I was able to reproduce this with the specified version of Newman 😄 

I'll update this thread when a fix is being worked on.

**Comment by htmtester** [comment]
Thanks a lot @kunagpal.

**Comment by htmtester** [comment]
@kunagpal any updates on this?

**Comment by kunagpal** [comment]
@htmtester This is being fixed in https://github.com/postmanlabs/newman/pull/1389 and will be available with the next Newman release 😄

**Comment by htmtester** [comment]
upgraded to newman 3.9.3 and the issue persists @kunagpal :(

**Comment by kunagpal** [comment]
@htmtester My bad, I wasn't precise enough on this. Newman v3.9.4 will go out with this fix in a few days. 😓

**Comment by htmtester** [comment]
ok np thanks

**Comment by kunagpal** [comment]
@htmtester This has been fixed with Newman v3.9.4 😄
