### ISSUE TITLE
Not taking enabled flag into account when applying environment variables

### ISSUE THREAD

**Issue by abreitenfeld** [postmanlabs/newman#1446]
1. Newman Version (can be found via `newman -v`): 3.9.3
 2. OS details (type, version, and architecture): mac OS High Sierra
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: newman should only apply environment values that are enabled
 5. Command / script used to run Newman: 
`newman run collection.json -e environment.json`

 6. Sample collection, and auxiliary files (minus the sensitive details): 
**environment.json**
```{
  "id": "c4fe0913-45c3-dde2-fe27-684112454828",
  "name": "Newman Env",
  "values": [
    {
      "enabled": true,
      "key": "BASE",
      "value": "https://www.nytimes.com",
      "type": "text"
    },
    {
      "enabled": false,
      "key": "BASE",
      "value": "http://example.com/",
      "type": "text"
    }
  ],
  "timestamp": 1519378142563,
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2018-02-23T09:29:13.071Z",
  "_postman_exported_using": "Postman/5.5.3"
}
```

**collection.json**

```{
	"info": {
		"name": "Newman Test",
		"_postman_id": "c74d0628-8aa6-2ab8-308f-0c4a86d40139",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Simple GET",
			"request": {
				"method": "GET",
				"header": [],
				"body": {},
				"url": {
					"raw": "{{BASE}}",
					"host": [
						"{{BASE}}"
					]
				},
				"description": ""
			},
			"response": []
		}
	]
}
```

 7. Screenshots (if applicable): N/A

Steps to reproduce

1. Run the given command
2. Note that the request is sent to `example.com` even though enabled is set to false

**Comment by aking1012** [comment]
I ran in to this one too.  I had a variable I moved from environment to global and disabled the environment variable in the Postman UI.  The old environment variable was instantiated first and overrode a global variable of the same name.  Postman ran the collection properly, but newman bombed out.  If I delete that JSON chunk in the environment file (all structures with false in them), then it works swimmingly.  I think we're talking about the same bug.

**Comment by shamasis** [comment]
@kamalaknn we need to support this

**Comment by codenirvana** [comment]
@abreitenfeld @aking1012 Thanks for reporting, this has been fixed in Newman v4.4.0.

For now, you have to update all instances of `"enabled": false` to `"disabled": true`.
We are working on fixing the environment export in the Postman app. 😅

**Comment by MattShawOnBI** [comment]
Seem this problem still exists with newman@5.3.2
the variables with "enabled":false are still being read :-(
