### ISSUE TITLE
Latest docker image breaks Basic Auth

### ISSUE THREAD

**Issue by gaigaslab** [postmanlabs/newman#1548]
1. 3.9.4 (worked in 3.9.3)
 2. MACOS
 3. Both
 3. May 24, 2018 10am
 4. Basic Auth embedded in postman image works
 5. newman run <image> -k
 6.
```
 {
	"info": {
		"_postman_id": "3c8e8799-7c5d-4a09-9bc4-13b40a1e24f1",
		"name": "<test name>",
		"description": "Our test",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "<name>",
			"event": [
				{
					"listen": "prerequest",
					"script": {
						"id": "2baa8935-2fa9-453e-9b0e-c213c99ddf87",
						"type": "text/javascript",
						"exec": [
							"const echoPostRequest = {",
							"  url: 'https:xxx',",
							"  method: 'POST',",
							"  header: request.headers,",
							"  body: {",
							"    mode: 'raw',",
							"    raw: request.data",
							"  }",
							"};",
							"",
							"pm.sendRequest(echoPostRequest, function(err, pcfResponse) {",
							"    pm.environment.set(\"pcfResponse\", JSON.stringify(xml2Json(pcfResponse.text())));",
							"});"
						]
					}
				},
				{
					"listen": "test",
					"script": {
						"id": "27a3cf07-0cb9-493e-a067-ca2fe1ff6649",
						"type": "text/javascript",
						"exec": [
							"pm.test(\"Responses match\", function() {",
							"    var pcfResponse = pm.environment.get(\"pcfResponse\");",
							"    var existingServiceResponse = JSON.stringify(xml2Json(pm.response.text()));",
							"    pm.expect(pcfResponse).to.equal(existingServiceResponse);",
							"});"
						]
					}
				}
			],
			"request": {
				"auth": {
					"type": "basic",
					"basic": [
						{
							"key": "password",
							"value": "<pass>",
							"type": "string"
						},
						{
							"key": "username",
							"value": "<user>",
							"type": "string"
						}
					]
				},
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"value": "text/xml"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ser=\"http://xxx\">\n    <soapenv:Body>\n        <xxx>\n            <rmRequest>\n                <policyControlDate>08/28/2017</policyControlDate>\n                <policyType>New_Policy_Issue</policyType>\n                <quoteDate>05/21/2018</quoteDate>\n                <ratingCategory>TaxSurch</ratingCategory>\n                <stateCode>US</stateCode>\n            </rmRequest>\n        </xxx>\n    </soapenv:Body>\n</soapenv:Envelope>"
				},
				"url": {
					"raw": "https://xxx",
					"protocol": "https",
					"host": [
						"<path>"
						
					],
					"port": "1024",
					"path": [
						"<path>",
						"<path>"
					]
				}
			},
			"response": []
		}
	]
}
 ```

7.  + npm install newman --global --no-spin
WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.3.2","npm":"2.14.12"})
WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.3.2","npm":"2.14.12"})
```
┌
  │ 'runtime~basic.auth: could not sign the request: binary is not a function', [TypeError: binary is not a function]
```

**Comment by kunagpal** [comment]
@gaigaslab This has been fixed in Newman v3.10.0 😄

**Comment by Nandhaks2** [comment]
I'm using newman v3.10.0 . I'm still getting this error when run from jenkins. It works fine if I run directly from postman. 
┌
  │ [90m'runtime~basic.auth: could not sign the request: 
  │ binary is not a function'[39m, [TypeError: binary is 
  │ not a function]
  └

Any help is very much appreciated. Thanks.
