### ISSUE TITLE
collection execution and script execution timeouts occur when api options timeout or timeoutScript are omitted

### ISSUE THREAD

**Issue by cchretien** [postmanlabs/newman#1626]
1. Newman Version (can be found via `newman -v`): **3.10.0**
 2. OS details (type, version, and architecture): **Windows 7 Enterprise 64Bit, node 8.11.3 64Bit**
 3. Are you using Newman as a library, or via the CLI? **Library**
 3. Did you encounter this recently, or has this bug always been there: Bug was **not present in 3.8.3**
 4. Expected behaviour: No timeouts during long collection or test script execution when options are omitted. This breaks backwards compatibility.

 5. Command / script used to run Newman: See attached script
[timeout-bug.js.txt](https://github.com/postmanlabs/newman/files/2194075/timeout-bug.js.txt)

 6. Sample collection, and auxiliary files (minus the sensitive details): See attached collection
[timeout.postman_collection.json.txt](https://github.com/postmanlabs/newman/files/2194073/timeout.postman_collection.json.txt)

 7. Screenshots (if applicable): See attached logs
[timeout-bug-loop.log](https://github.com/postmanlabs/newman/files/2194063/timeout-bug-loop.log)
[timeout-bug-client-delay.log](https://github.com/postmanlabs/newman/files/2194065/timeout-bug-client-delay.log)

**Comment by cchretien** [comment]
One thing I noticed is if I explicitly set the timeoutScript to 0 it still triggers a timeout as if it were omitted.

**Comment by kunagpal** [comment]
@cchretien This is because the global timeout still takes precedence in this case, you'll have to set `timeout: 0` explicitly. A similar case has been discussed and resolved here: https://community.getpostman.com/t/error-callback-timed-out-why/1508/19

**Comment by codenirvana** [comment]
@cchretien This has been fixed in Newman v4.0.0.

**Comment by cchretien** [comment]
Still broken. Using the same collection and toying with the same script that i've attached originally.
```
var Newman = require('newman');

var opts = {
    collection: './timeout.postman_collection.json',
    folder: 'client delay',
    environment: {
        "id": "d2dce2c9-3ada-4c8f-9af9-0281eb6d3336",
        "name": "timeout",
        "values": [
            {
                "key": "LOOPS",
                "value": "19",
                "description": "",
                "type": "text",
                "enabled": true
            },
            {
                "key": "TIMEOUT",
                "value": "180000",
                "description": "",
                "type": "text",
                "enabled": true
            }
        ],
        "_postman_variable_scope": "environment",
        "_postman_exported_at": "2018-07-13T18:49:04.858Z",
        "_postman_exported_using": "Postman/6.0.10"
    },
    delayRequest: 100,
    timeout: 0,
    timeoutRequest: 180000,
    timeoutScript: 0,
    insecure: true,
    bail: false,
    suppressExitCode: true,
    reporters: ['cli'],
    reporter: {
        cli: {
            noBanner: true,
            noSummary: false
        }
    }
};


function runNewman(opts) {
    var numErrs = 0;
    try {
        Newman.run(opts, function (err, summary) {
            console.log('collection run complete!');

            if (err) {
                numErrs += 1;
                console.log(`encountered error`, numErrs);
                //console.log(err);
                console.log(err.stack);
            }
        });

    } catch (e) {
        numErrs =+ 1;
        console.log(`encountered error`, numErrs);
        //console.log(e);
        console.log(e.stack);
    }

}

// script timeout with defaults
console.log('run script timeout\n********');
runNewman(opts);
```

Output:

```
c:\Work\newman>node --version
v8.11.3

c:\Work\newman>node_modules\.bin\newman -v
4.0.0

c:\Work\newman>
c:\Work\newman>
c:\Work\newman>
c:\Work\newman>node timeout-bug.js
run script timeout
********
timeout

□ client delay
└ Delay Response with client delay
  GET https://postman-echo.com/delay/10 [200 OK, 362B, 11.1s]

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        0 │        0 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 0ms                       │
├───────────────────────────────────────────────┤
│ total data received: 14B (approx)             │
├───────────────────────────────────────────────┤
│ average response time: 11.1s                  │
└───────────────────────────────────────────────┘
collection run complete!
encountered error 1
Error: Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at PostmanSandbox.emitter._dispatch (c:\Work\newman\node_modules\uvm\lib\uvm\bridge.js:113:16)
    at PostmanSandbox.dispatch (c:\Work\newman\node_modules\uvm\lib\uvm\index.js:104:30)
    at PostmanSandbox.execute (c:\Work\newman\node_modules\postman-sandbox\lib\index.js:106:14)
    at PostmanCollectionRun.<anonymous> (c:\Work\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:289:27)
    at c:\Work\newman\node_modules\async\dist\async.js:1135:9
    at replenish (c:\Work\newman\node_modules\async\dist\async.js:1011:17)
    at c:\Work\newman\node_modules\async\dist\async.js:1016:9
    at _asyncMap (c:\Work\newman\node_modules\async\dist\async.js:1133:5)

c:\Work\newman>
```

**Comment by cchretien** [comment]
@kunagpal,

Can this be reopened and fixed?
