### ISSUE TITLE
Newman doesn't appear to be able to download Postman Collections in Node 12

### ISSUE THREAD

**Issue by deltamualpha** [postmanlabs/newman#1991]
1. Newman Version (can be found via `newman -v`): 4.4.1
 2. OS details (type, version, and architecture): macOS 10.14.4; node 12.1.0
 3. Are you using Newman as a library, or via the CLI? **CLI**
 3. Did you encounter this recently, or has this bug always been there: New installation
 4. Expected behaviour: It runs a collection
 5. Command / script used to run Newman: `newman run https://raw.githubusercontent.com/heremaps/postman-collections/master/weather.postman_collection`
 6. Sample collection, and auxiliary files (minus the sensitive details):
 7. Screenshots (if applicable):

Node 12.1.0:
```
$ newman run https://raw.githubusercontent.com/heremaps/postman-collections/master/weather.postman_collection
newman: Newman v4 deprecates support for the v1 collection format
  Use the Postman Native app to export collections in the v2 format

newman

Weather API

→ Severe Weather Alerts
_tls_wrap.js:513
  self._destroySSL();
       ^

TypeError: Cannot read property '_destroySSL' of undefined
    at Timeout.destroySSL [as _onTimeout] (_tls_wrap.js:513:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Node 10:
```
$ newman run https://raw.githubusercontent.com/heremaps/postman-collections/master/weather.postman_collection
newman: Newman v4 deprecates support for the v1 collection format
  Use the Postman Native app to export collections in the v2 format

newman

Weather API

→ Severe Weather Alerts
  GET https://weather.cit.api.here.com/weather/1.0/report.json?product=alerts&name=Chicago&app_id={{YOUR_APP_ID}}&app_code={{YOUR_APP_CODE}} [401 Unauthorized, 550B, 156ms]
... etc etc etc
```

Node 12:
```
$ newman run weather.postman_collection
newman: Newman v4 deprecates support for the v1 collection format
  Use the Postman Native app to export collections in the v2 format

newman

Weather API

→ Severe Weather Alerts
  GET https://weather.cit.api.here.com/weather/1.0/report.json?product=alerts&name=Chicago&app_id={{YOUR_APP_ID}}&app_code={{YOUR_APP_CODE}} [401 Unauthorized, 550B, 137ms]
... etc etc etc
```

**Comment by deltamualpha** [comment]
(Original issue wasn't encountered with the weather collection, but it showcases identical behavior.)

**Comment by deltamualpha** [comment]
Ah, running them from a local file succeeds.

**Comment by ousmaneNdiaye** [comment]
The same problem happened to my build on circleci three days ago ... 
Newman always fails with the error : 
```  self._destroySSL();
       ^
TypeError: Cannot read property '_destroySSL' of undefined
    at Timeout.destroySSL [as _onTimeout] (_tls_wrap.js:513:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by ousmaneNdiaye** [comment]
I found a solution to fix it on CircleCi, sticking node to the lts version : 

```
#.circleci/config.yml
version: 2.1
jobs:
    build:
        docker:
        - image: circleci/node:lts
[...]
```

**Comment by Exodus** [comment]
I'm having the same issue with the current latest version in homebrew:
```
node --version
v12.1.0
```

When running:
```
newman run https://api.getpostman.com/collections/<redacted>\?apikey\=<redacted> --environment https://api.getpostman.com/environments/<redacted>\?apikey\=<redacted>
```

Output:
```
_tls_wrap.js:513
  self._destroySSL();
       ^

TypeError: Cannot read property '_destroySSL' of undefined
    at Timeout.destroySSL [as _onTimeout] (_tls_wrap.js:513:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Downgrading to the LTS version (`v10.15.3`) runs the collection without issue.

**Comment by shamasis** [comment]
Yep. We are observing anomalies with Node12. @codenirvana - maybe we can put some of our observations updated here.

I suggest downgrading to node 11 / 10 - until we figure out what changed in 12.

**Comment by MauriceS** [comment]
I observed the same problem in Bitbucket Pipelines, Newman 4.4.1, and latest node image in Bitbucket Pipelines. It failed in the middle of the test (after 300 of 905 tests). Specifying Node 10.15 fixed the problem.

_tls_wrap.js:534
  self._destroySSL();
       ^
TypeError: Cannot read property '_destroySSL' of undefined
    at Timeout.destroySSL [as _onTimeout] (_tls_wrap.js:534:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by codenirvana** [comment]
This is fixed in Newman v4.5.0

**Comment by juchom** [comment]
Issue is still present in 4.5.0, my tests are working fine and then this exception appears:

```
TypeError: Cannot read property '_destroySSL' of undefined
    at Timeout.destroySSL [as _onTimeout] (_tls_wrap.js:534:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
PS C:\Users\Administrator> newman -v
4.5.0
```

**Comment by janniswarnat** [comment]
I am also still getting the error with newman 4.5.0 and Node version v12.2.0:

```
_tls_wrap.js:534
  self._destroySSL();
       ^

TypeError: Cannot read property '_destroySSL' of undefined
    at Timeout.destroySSL [as _onTimeout] (_tls_wrap.js:534:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Not sure if this is relevant: In my case it comes up when querying a URL with a self-signed SSL certificate. Can this issue be re-opened or should @juchom or I open a fresh issue?

Best regards

Jannis

**Comment by shamasis** [comment]
Are you facing issue while fetching collection from url or while running a collection that has this url? @codenirvana if @janniswarnat says it’s the latter, then let’s track that as a separate issue

**Comment by janniswarnat** [comment]
A test inside a local collection fails. I will try to reproduce the error
 with a minimal example and open a new issue.

**Comment by janniswarnat** [comment]
New issue has been created with info on how to reproduce:

#2015 

Update to one of my comments: The error is not related to self-signed certificates.

**Comment by csvan** [comment]
Confirming that downgrading to nodejs 10.15 solves this issue for me (see repro: https://github.com/postmanlabs/newman/issues/2015#issuecomment-495893273)

**Comment by Nidhisachan** [comment]
I am still getting the same issue while generating the URL via sharing collection:
newman: Newman v4 deprecates support for the v1 collection format
  Use the Postman Native app to export collections in the v2 format
