### ISSUE TITLE
Verbose option in HTML output [Feature Request]

### ISSUE THREAD

**Issue by ghost** [postmanlabs/newman#251]
It would be nice to have the option for a more verbose output in the generated HTML file to include details of the request being made (URL & maybe post body). I currently have Newman set to trigger an email with a URL to the HTML page should the test fail and it'd be handy to have the exact test there rather than having to double check the collection file

**Comment by czardoz** [comment]
Newman now has a verbose mode, ``-O`` that can be used to output information about the exact HTTP request that was sent and the response that was received. Does that do the trick for you?

https://github.com/postmanlabs/newman/blob/develop/bin/newman#L48

**Comment by Evesy** [comment]
I was ideally looking for a more verbose output inside of the existing HTML template (so viewing said page will provide info of the actual tests being performed), however I may be able to do something with the new mode listed above

**Comment by mstaalesen** [comment]
@czardoz Are there any reasons as to why the Request Body for a POST request is not part of the verbose report?

**Comment by czardoz** [comment]
@mstaalesen, was a bug (#311), just fixed it.

**Comment by mstaalesen** [comment]
@czardoz Cheers! Excuse me for not checking the current issues before asking!

**Comment by srbangre** [comment]
Issue still exists. why did you close my ticket #311 and tagged it with this one when it was not worked upon?

**Comment by czardoz** [comment]
@srbangre #311 was about `--outputFileVerbose`, not about HTML report. It has been fixed in v2.0.1

This issue is about adding the same information in the HTML report. That has not been worked upon, and therefore this issue is not closed.

**Comment by srbangre** [comment]
#311 is not working. i am still having issues with outputFileverbose not printing request body.

**Comment by kurtfm** [comment]
This would be awesome!  I was looking for this... or some way to correctly results between the two files easier.

**Comment by kunagpal** [comment]
@kurtfm @srbangre @ghost @mstaalesen Newman does support a verbose report option via the [JSON reporter](https://github.com/postmanlabs/newman#json-reporter-options), which provides comprehensive collection run information.

**Comment by miniseb** [comment]
Hello @kunagpal 
in the Json reporter, i always have an empty array in the response property. How to enable logging the response body of all requests ?
